{
  "version": "3.8",
  "services": {
    "agi-eval-api": {
      "build": {
        "context": ".",
        "dockerfile": "Dockerfile"
      },
      "ports": [
        "8080:8080"
      ],
      "environment": [
        "ENVIRONMENT=production",
        "LOG_LEVEL=INFO",
        "REDIS_URL=redis://redis:6379",
        "DATABASE_URL=postgresql://postgres:password@postgres:5432/agi_eval"
      ],
      "depends_on": [
        "redis",
        "postgres"
      ],
      "restart": "unless-stopped",
      "healthcheck": {
        "test": [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/health"
        ],
        "interval": "30s",
        "timeout": "10s",
        "retries": 3,
        "start_period": "40s"
      },
      "deploy": {
        "resources": {
          "limits": {
            "cpus": "2.0",
            "memory": "4G"
          },
          "reservations": {
            "cpus": "1.0",
            "memory": "2G"
          }
        }
      }
    },
    "agi-eval-dashboard": {
      "build": {
        "context": "./dashboard",
        "dockerfile": "Dockerfile"
      },
      "ports": [
        "3000:3000"
      ],
      "environment": [
        "REACT_APP_API_URL=http://localhost:8080",
        "NODE_ENV=production"
      ],
      "restart": "unless-stopped"
    },
    "redis": {
      "image": "redis:7-alpine",
      "ports": [
        "6379:6379"
      ],
      "volumes": [
        "redis_data:/data"
      ],
      "restart": "unless-stopped",
      "command": "redis-server --appendonly yes"
    },
    "postgres": {
      "image": "postgres:15",
      "environment": [
        "POSTGRES_DB=agi_eval",
        "POSTGRES_USER=postgres",
        "POSTGRES_PASSWORD=password"
      ],
      "volumes": [
        "postgres_data:/var/lib/postgresql/data"
      ],
      "ports": [
        "5432:5432"
      ],
      "restart": "unless-stopped"
    },
    "nginx": {
      "image": "nginx:alpine",
      "ports": [
        "80:80",
        "443:443"
      ],
      "volumes": [
        "./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro",
        "./deployment/nginx/ssl:/etc/nginx/ssl:ro"
      ],
      "depends_on": [
        "agi-eval-api",
        "agi-eval-dashboard"
      ],
      "restart": "unless-stopped"
    },
    "prometheus": {
      "image": "prom/prometheus:latest",
      "ports": [
        "9090:9090"
      ],
      "volumes": [
        "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      ],
      "restart": "unless-stopped"
    },
    "grafana": {
      "image": "grafana/grafana:latest",
      "ports": [
        "3001:3000"
      ],
      "environment": [
        "GF_SECURITY_ADMIN_PASSWORD=admin"
      ],
      "volumes": [
        "grafana_data:/var/lib/grafana",
        "./monitoring/grafana:/etc/grafana/provisioning:ro"
      ],
      "restart": "unless-stopped"
    }
  },
  "volumes": {
    "redis_data": {},
    "postgres_data": {},
    "grafana_data": {}
  },
  "networks": {
    "default": {
      "name": "agi_eval_network"
    }
  }
}