global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'agi-eval-sandbox'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # AGI Evaluation Sandbox API
  - job_name: 'agi-eval-api'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Celery metrics
  - job_name: 'celery'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics/celery'

  # Custom application metrics
  - job_name: 'agi-eval-custom'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics/custom'
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'