name: 🐛 Bug Report
description: Report a bug to help us improve
title: "🐛 [Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! This form will help us gather the information needed to investigate and fix the issue.

  - type: checkboxes
    id: preliminary_checks
    attributes:
      label: 🔍 Preliminary Checks
      description: Please confirm you have completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have checked the documentation for potential solutions
          required: true
        - label: I am using the latest version of the software
          required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened vs what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened instead
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🧩 Component
      description: Which component is affected?
      options:
        - API / Backend
        - Dashboard / Frontend
        - CLI Tool
        - Documentation
        - CI/CD Pipeline
        - Docker / Deployment
        - Database
        - Cache / Redis
        - Monitoring
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround exists
        - Medium - Significant issue, affects functionality
        - High - Major issue, blocks important functionality
        - Critical - System is unusable or data loss occurs
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - Browser: [e.g., Chrome 115, Firefox 116] (if applicable)
        - Docker Version: [e.g., 24.0.0] (if applicable)
        - Python Version: [e.g., 3.11.0] (if applicable)
        - Node.js Version: [e.g., 18.17.0] (if applicable)
        - Version/Commit: [e.g., v1.2.3 or commit hash]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs and Error Messages
      description: Any relevant log output or error messages
      placeholder: |
        ```
        Paste error messages, logs, or stack traces here
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 🖼️ Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: textarea
    id: additional_context
    attributes:
      label: 📎 Additional Context
      description: Any other context about the problem
      placeholder: |
        - Does this happen consistently or intermittently?
        - Did this work in a previous version?
        - Any recent changes to your setup?
        - Related issues or PRs?

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Would you like to contribute to fixing this issue?
      options:
        - label: I would be willing to submit a PR to fix this issue
        - label: I would like to be assigned to work on this issue
        - label: I need help understanding how to fix this issue

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🚀 What happens next?
        
        1. **Triage**: Our team will review and label this issue
        2. **Investigation**: We'll investigate and may ask for more information
        3. **Fix**: Once identified, we'll work on a fix
        4. **Testing**: The fix will be tested thoroughly
        5. **Release**: The fix will be included in the next release
        
        Thank you for helping us improve the AGI Evaluation Sandbox! 🙏