name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Use a clear and descriptive title
        - Provide as much detail as possible

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I am using a supported version of the software
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - Python Version: [e.g., 3.11.0]
        - Package Version: [e.g., 0.1.0]
        - Docker Version: [e.g., 24.0.0] (if applicable)
        - Browser: [e.g., Chrome 118.0] (if web-related)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      render: shell
      placeholder: Paste error logs here...

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration files or settings (remove sensitive data)
      render: yaml
      placeholder: |
        # paste relevant config here
        # make sure to remove any sensitive information

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workarounds
        - High - Major functionality broken
        - Critical - System unusable
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, videos, or additional information...