name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please fill out the sections below to help us understand your request.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: I have read the project roadmap and documentation
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the pain point?
      placeholder: Describe the problem you're trying to solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions or features you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for adoption
        - Critical - Blocking current use case
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Very Complex - Major architectural changes
        - Unknown - Not sure

  - type: checkboxes
    id: components
    attributes:
      label: Affected Components
      description: Which parts of the system would this feature affect?
      options:
        - label: API Backend
        - label: Web Dashboard
        - label: CLI Tool
        - label: Evaluation Engine
        - label: Database Schema
        - label: Docker Configuration
        - label: Documentation
        - label: CI/CD Pipeline

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that I can [benefit]
        2. When [scenario], this feature would allow me to [action]
        3. This would be useful for [specific workflow/process]

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Any mockups, examples, or references that would help explain the feature
      placeholder: Links to mockups, similar features in other tools, code examples, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'd like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide domain expertise

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: Links to research, related issues, technical considerations, etc.